debug: false
uuid: 615e08f1-8260-4a7e-84b0-1492d5b78fa6
token_id: W0aUoFui3HM2ZWyJ
token: O4PIWxzUxpQJDkNTj7QBni40ZmUTphWVFR6IUQVzuYMgOZhpnTj6aKonAD7uQ7GQ

api:
  host: 0.0.0.0
  port: 8081
  ssl:
    enabled: false
  upload_limit: 100

system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022

allowed_mounts: []

# URL del panel principal
remote: 'http://9n3plm-8080.csb.app'
# ⚠️ Eliminado timezone (causaba bug en Koyeb)
